# Generated by Django 5.2.3 on 2025-06-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_room', models.IntegerField()),
                ('pg_name', models.CharField(max_length=100)),
                ('pg_image_url', models.URLField(blank=True, null=True)),
                ('facility', models.TextField()),
                ('amenity', models.TextField()),
                ('room_type', models.CharField(max_length=50)),
                ('is_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('room_location', models.CharField(max_length=200)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pg_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='owner.owner')),
            ],
        ),
    ]
