# Generated by Django 5.2 on 2025-06-24 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('pg_name', models.CharField(max_length=255)),
                ('pg_owner', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=100)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.room')),
            ],
        ),
    ]
