# Generated by Django 5.2.3 on 2025-06-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_phone', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('current_address', models.TextField()),
            ],
        ),
    ]
