# Generated by Django 5.2.3 on 2025-06-21 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_room'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
            ],
        ),
    ]
